### ISSUE TITLE
May I ask

### ISSUE THREAD

**Issue by cx20011026** [silent-rookie/Dynamic_Load_Balancing_Routing_Algorithm#2]
May I ask if you have implemented deep reinforcement learning for satellite routing based on the NS3 simulation?

**Comment by silent-rookie** [comment]
not  yet

**Comment by cx20011026** [comment]
我目前是想结合深度强化学习和ns3做卫星路由，现在处于瓶颈期，请问您是否可以提供一些帮助，可以有chang

**Comment by silent-rookie** [comment]
> 我目前是想结合深度强化学习和ns3做卫星路由，现在处于瓶颈期，请问您是否可以提供一些帮助，可以有chang

github上应该有类似的项目，你可以搜索一下，我听过有个同学搜到过相关的项目

**Comment by cx20011026** [comment]
我仅仅只找到深度强化学习做卫星路由的，但并不是在ns3进行仿真的项目，请问方便加您一个联系方式吗，想请教请教您

**Comment by ujunhui0** [comment]
> > 我目前是想结合深度强化学习和ns3做卫星路由，现在已达到阈值，请问您是否可以提供一些帮助，可以有改变
> 
> github上应该有类似的项目，你可以搜一下，我听一个同学搜到过相关的项目

请问大佬相关卫星网络路由结合深度学习的代码有链接吗？我在GitHub上没找到。

**Comment by silent-rookie** [comment]
不好意思，这个帮不到您了，我只是在当时听到有同学是做这个方向的，他说在GitHub上有找到。发自我的 iPhone在 2025年4月5日，11:33，ujunhui0 ***@***.***> 写道：﻿
  

我目前是想结合深度强化学习和ns3做卫星路由，现在已达到阈值，请问您是否可以提供一些帮助，可以有改变

github上应该有类似的项目，你可以搜一下，我听一个同学搜到过相关的项目

请问大佬相关卫星网络路由结合深度学习的代码有链接吗？我在GitHub上没找到。—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>



ujunhui0 left a comment (silent-rookie/Dynamic_Load_Balancing_Routing_Algorithm#2)


我目前是想结合深度强化学习和ns3做卫星路由，现在已达到阈值，请问您是否可以提供一些帮助，可以有改变

github上应该有类似的项目，你可以搜一下，我听一个同学搜到过相关的项目

请问大佬相关卫星网络路由结合深度学习的代码有链接吗？我在GitHub上没找到。

**Comment by silent-rookie** [comment]
﻿﻿不好意思，这个帮不到您了，我只是在当时听到有同学是做这个方向的，他说在GitHub上有找到。发自我的 iPhone在 2025年4月5日，11:33，ujunhui0 ***@***.***> 写道：﻿
  

我目前是想结合深度强化学习和ns3做卫星路由，现在已达到阈值，请问您是否可以提供一些帮助，可以有改变

github上应该有类似的项目，你可以搜一下，我听一个同学搜到过相关的项目

请问大佬相关卫星网络路由结合深度学习的代码有链接吗？我在GitHub上没找到。—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you modified the open/close state.Message ID: ***@***.***>



ujunhui0 left a comment (silent-rookie/Dynamic_Load_Balancing_Routing_Algorithm#2)


我目前是想结合深度强化学习和ns3做卫星路由，现在已达到阈值，请问您是否可以提供一些帮助，可以有改变

github上应该有类似的项目，你可以搜一下，我听一个同学搜到过相关的项目

请问大佬相关卫星网络路由结合深度学习的代码有链接吗？我在GitHub上没找到。
